### ISSUE TITLE
demo not working ? [flutter_hue]

### ISSUE THREAD

**Issue by tempo-riz** [babincc/flutter_workshop#9]
Hey I just cloned your repo to try the demo,
the only modifications I did was replacing the placeholders with the
clientId, clientSecret that I got from dev console
and redirectUri with https://oauth.pstmn.io/v1/browser-callback

When I try the app, on my physical or emulated android.
First I tried to call discoverBridges() (via the button) 
and I get the following output without anything else happening : 

```
E/Dart    (28945): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.
E/Dart    (28945): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.
E/Dart    (28945): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.
E/Dart    (28945): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.
```

I tried the official philps hue app and everything works as expected with it 
I got a bridge with a play kit [link](https://www.digitec.ch/fr/s1/product/philips-hue-play-kit-de-base-extension-lampe-de-table-9414900)

Thank you for developping this plugin, hope you can help !

**Comment by tempo-riz** [comment]
edit : apparently it does work but one time on 5-6 tries, 
then I established remote contact succesfully (so it seems)
and the fetch Network button throws 
`_TypeError (type '_Map<String, dynamic>' is not a subtype of type 'List<dynamic>?' in type cast)`
at await hueNetwork?.fetchAll();

**Comment by babincc** [comment]
The `redirectUri` is what you put in your Hue dev console when you made your account. It should be formatted like this `[scheme]://[domain]` - Example `flutterhue://auth`

This is used on Philips Hue's side when the user tells Hue that your app has permission to log into their account. Once they log in and approve your app, Philips Hue redirects them to the redirect URI from your dev console; your app will capture that redirect with deep linking and open your app.

Does this help at all?

**Comment by tempo-riz** [comment]
Yes, but the url I provided isn't valid ? I think it is with sheme being https, correct me if I'm wrong, my question was mostly related to the errors I got !

**Comment by babincc** [comment]
What is the URL you provided? Is that a Postman testing environment? Or is that what you would use in your final product?

Also, what are you trying to get your app to do right now? Are you trying to establish a remote connection (your phone not on the same network as your Philips Hue device) or a local connection (everything on the same wifi)?

**Comment by tempo-riz** [comment]
https://oauth.pstmn.io/v1/browser-callback
Yes the public postman oauth, I think I can use it, at least for testing it should work, I can get the params from url

**Comment by babincc** [comment]
Are you familiar with deep linking? I'm not sure Postman is the right thing to use in this situation.

**Comment by tempo-riz** [comment]
My goal is to control my lights, 
Both with and without remote connection, for now none of the 2 methods are working, maybe I'm missing something ?

**Comment by tempo-riz** [comment]
When you run your example with latest flutter sdk and android version is it working for you?

**Comment by babincc** [comment]
Yes, it is working for me. Is your app running on a device that is on the same network as your Philips Hue bridge?

**Comment by tempo-riz** [comment]
> Are you familiar with deep linking? I'm not sure Postman is the right thing to use in this situation.

Not really, If you have any ressource to link maybe it could help, thanks :)

**Comment by babincc** [comment]
> > Are you familiar with deep linking? I'm not sure Postman is the right thing to use in this situation.
> 
> Not really, If you have any ressource to link maybe it could help, thanks :)

Here is a link for deep linking in general
https://docs.flutter.dev/ui/navigation/deep-linking

This is a link for setting up a remote connection with this SDK. The SDK should handle the deep linking for you
https://github.com/babincc/flutter_workshop/blob/master/packages/flutter_hue/remote_connection_instructions.md

**Comment by tempo-riz** [comment]
> Yes, it is working for me. Is your app running on a device that is on the same network as your Philips Hue bridge?

Yes the bridge with ethernet and my phone on wifi, I will do more testing tomorrow thanks for the docs

**Comment by tempo-riz** [comment]
okay so I tried with a new redirect uri, I updated it in hue's dev console,
Tell me if something seems wrong to you :

this is my app id : com.example.jdr_ia
so i used it like this in my manifest
<data android:scheme="com.example.jdr_ia"/>
and my redirect uri : "com.example.jdr_ia://auth"

I can detect my bridge with "discover bridges" button,
then I can "first contact"
then I tried 2 things : 
- directly "fetch network" (if I want to connect without remote connection, is that right ?)
which throws this 
```
E/flutter (23538): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type '_Map<String, dynamic>' is not a subtype of type 'List<dynamic>?' in type cast
E/flutter (23538): #0      new EntertainmentConfiguration.fromJson (package:flutter_hue/domain/models/entertainment_configuration/entertainment_configuration.dart:69:45)
E/flutter (23538): #1      HueNetwork.fetchAllType (package:flutter_hue/domain/models/hue_network.dart:459:49)
E/flutter (23538): <asynchronous suspension>
E/flutter (23538): #2      HueNetwork.fetchAll (package:flutter_hue/domain/models/hue_network.dart:309:7)
E/flutter (23538): <asynchronous suspension>
```
- "establish remote connection" which opens the official hue app and asks permission, when I accept promp it doesnt redirect to my app but stay in hue (official)

**Comment by babincc** [comment]
> directly "fetch network" (if I want to connect without remote connection, is that right ?)
which throws this

I have published a new version (1.2.1) that should fix the above issue. You are testing my code with Philips Hue devices that I don't have. You may run into other bugs like this that I missed because I just never came across them in testing. Please let me know about them so I can get them fixed.

> "establish remote connection" which opens the official hue app and asks permission, when I accept promp it doesnt redirect to my app but stay in hue (official)

This issue could be a number of things. The first thing I would do is stop your app emulation, run `flutter clean` in the console, and then `flutter pub get`. Then, start your app back up and see if it works. Deep linking can be a little tricky and when you change your Android manifest, it often times needs to be cleaned and rebuilt.

If that doesn't work, it could be the underscore in your URL scheme. It should work, but some people warn of odd behavior with special characters.

Try these ideas, and come back to me if it still isn't working. I'm happy to help!

**Comment by tempo-riz** [comment]
Thank you for your time and quick response !

The 1.2.1 fixed the fetchNetwork, now I can control the lamps locally !

I updated my scheme, which is now correctly redirecting to my app, it was probably an underscore issue.

I still have 2 issues :

1. The discover bridges fonction only work once, when I install the app, after this it returns empty array, is that expected behavior ? 
I have to reinstall the app to make it work once again
I don't know if related but I get the following error messages in both cases :

```E/Dart    (10226): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.
E/Dart    (10226): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.
E/Dart    (10226): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.```

2. When I try to connect remotely, when redirected to my app, it doesn't seem to trigger in the uriLinksStream.listen()

I checked that with prints/breakpoint that never got triggered, it should after the redirect ? Or am I wrong ?

**Comment by babincc** [comment]
Once a bridge has been connected to, it will not show up again when discovering bridges. To find bridges that you have already connected to, use `fetchSavedBridges()`.

I'm not sure why `uriLinksStream.listen()` wouldn't be called. Is your code public so I can look at it?

**Comment by tempo-riz** [comment]
okay `fetchSavedBridges()` works, I thougt `maintain()` and `maintainBridges() ` were already calling it

for the stream.listen() I created a minimal example based on your example [here](https://github.com/tempo-riz/flutter-hue-playground)

**Comment by babincc** [comment]
I don't see why it wouldn't be working for you. A few questions:

- Is `playground://auth` exactly what you put in your Hue dev console?
- Does anything in `uriLinkStream.listen()` print for you? If so, where does it stop?
- What happens when establishing a remote connection? Does it open Hue's website, get you to log in, and send you back to the app?

**Comment by tempo-riz** [comment]
- I double checked the hue dev console it is correct
- No it doesnt trigger, I even tried this to display it in a widget but nothing happens
```
deepLinkStream = uriLinkStream.listen(
      (Uri? uri) {
        setState(() {
          txt = "uri is null";
        });
        if (uri == null) return;
        setState(() {
          txt = uri.toString();
        });
```
- it opens the prompt in the hue's mobile app since I also have it on my phone, I accept it and it returns to my app without triggering the .listen()

**Comment by babincc** [comment]
After a lot of experimenting, I believe this line is causing your `uriLinkStream.listen()` not to be called:

`<uses-permission android:name="android.permission.INTERNET" />`

It is the second line in your Android manifest. Remove that line entirely, and run `flutter clean` and `flutter pub get`; then when you start up your app, it should work.

**Comment by tempo-riz** [comment]
I tried removing the line from manifest, 
runned flutter clean, flutter pub get,
uninstalled app from my phone
flutter run
i'm on wifi, sucessfully first contact
then tried to establish remote contact
and listen() is still not triggered...

does it work for you ? on what device ?

**Comment by babincc** [comment]
It works for me on all devices. 

If you just do a local connection, are you able to control the lights?

Can you try remote connection again, and give me the whole console printout?

**Comment by tempo-riz** [comment]
Locally yes, everything works as expected, I can use all the features showcased in the demo.

sure, here is the console output
[logs.txt](https://github.com/babincc/flutter_workshop/files/11779807/logs.txt)

**Comment by babincc** [comment]
I don't see anything obvious to me. I do see this error:

```
E/flutter (18210): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
E/flutter (18210): #0      List.first (dart:core-patch/growable_array.dart:343:5)
E/flutter (18210): #1      _HomePageState.fetchSavedBridges (package:playground/main.dart:408:62)
E/flutter (18210): <asynchronous suspension>
```

That could have something to do with it. Also, it is possible some other package is intercepting your incoming deep link. 

If you are plugging the Flutter Hue SDK into your app that has lots of other code and packages, the best thing to do is work on a separate app that is just like the example app. Then, if you can get that working, add more to it until you find out what breaks it.

**Comment by tempo-riz** [comment]
I think this error might be because I tried to call fetchSavedBridges on a fresh install so there was no bridge saved...

To be 100 % sure it's not related to others packages i'm still using [this repo](https://github.com/tempo-riz/flutter-hue-playground) to make my tests

**Comment by tempo-riz** [comment]
Do you have the official philips hue app or does the redirect opens your web browser ?

**Comment by babincc** [comment]
The redirect should open in your browser.

**Comment by tempo-riz** [comment]
Okay so I just tried to uninstall the [philips hue app](https://play.google.com/store/apps/details?id=com.philips.lighting.hue2) and it seems that it was because of it.
when I had the app the prompt was opening in this app and callback not triggered after it
now that I dont have it anymore prompt opens in browser and callback works.

It is still problematic tho, because most of philips hue users have the app...

**Comment by tempo-riz** [comment]
A solution for this could be to use [webview](https://pub.dev/packages/webview_flutter) to handle the auth process, this way we never leave the app in the first place !

**Comment by tempo-riz** [comment]
I tried using webview, it works **but** the google sign in doesnt...

**Comment by tempo-riz** [comment]
I tried use a web callback for example : https://oauth.pstmn.io/v1/browser-callback 
then the user would copy/paste to retrieve the params.
but another intresting thing happens, maybe it is intended i'm not an expect on the topic...

I dont get a pcke code when redirect is opened in philip hue's app : 
this is how the parameters look without the app :
` /callback/?source=app&state=...&code=...`
and when redirected via the app (opens hue's app then browser on succes)
`/callback/?pkce=...&code=...&state=...`

 If you have an explanation of this don't hesitate !

**Comment by babincc** [comment]
I have looked extensively into this. Everything works as expected if the Hue app is not installed on the user's device. If the Hue app is installed, it intercepts the URL; in this case, remote access is granted, but it cannot send the user back to your app. This issue is on Philips Hue's end, and I cannot think of a way around it. If the user is not sent back to your app, it doesn't receive the token, and cannot use the remote access that it has been granted. I've reached out to Philips Hue for this issue and others I have had, and I have never gotten a response. I fear that they are not putting any resources into helping third-party developers, and we are on our own.

**Comment by tempo-riz** [comment]
Thank you for looking into it ! 
yeah the redirect doesnt work as expected, so I tried to use web callback instead of redirecting to my app, which works but as previously said the pkce is not present in response, is it mandatory ? If not how do I disable it ?

**Comment by babincc** [comment]
Yes the pkce is mandatory. It is how Philips Hue and your app confirm they are talking to each other. It prevents certain attacks.

**Comment by babincc** [comment]
Closing due to inactivity. If you still need help, you can re-open this issue.
